[theme]
base="light"
font="monospace"
primaryColor="#7BA46C"#7BA46C #74512D
backgroundColor="#FFFFFF"#FFFFFF #FEFAF6
secondaryBackgroundColor="#ABD1C6"#ABD1C6 #AF8F6F
textColor="#004643"#004643 #543310

